repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace
      - id: end-of-file-fixer     # Ensures newline at end of file
      - id: check-yaml            # Checks YAML file validity
      - id: check-json            # Ensures JSON files are valid
      - id: flake8                # Python code linting
      - id: black                 # Code formatter

  - repo: local
    hooks:
      - id: custom-file-check
        name: "Custom File Content Check"
        entry: python custom_check.py
        language: system
        files: ".*"
  - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
    rev: v3.9.2  # You can specify the latest version here
    hooks:
      - id: flake8
        files: \.py$
  - repo: https://github.com/pre-commit/mirrors-black
    rev: v22.1.0
    hooks:
      - id: black
        language_version: python3
        files: \.py$

